2021-02-12 10:59:11,189:__main__:INFO:Token file exists and created today
2021-02-12 10:59:11,191:__main__:INFO:Initializing session with token..
2021-02-12 10:59:11,192:__main__:INFO:Calculating everything before executing orders..
2021-02-12 10:59:11,193:__main__:INFO:Calculating weekly and monthly expiry dates..
2021-02-12 10:59:11,194:__main__:INFO:weekly expiry is : 18Feb2021, monthly expiry is: 25Feb2021
2021-02-12 10:59:12,523:__main__:INFO:StrikePrice computed as : 15250
2021-02-12 10:59:12,524:__main__:INFO:Input of get_eID fn : NIFTY, ce,18Feb2021,15250
2021-02-12 10:59:12,525:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-12 10:59:13,814:__main__:INFO:Exchange Instrument ID : 39549, {'oty': ['CE'], 'ss': ['39549']}
2021-02-12 10:59:13,816:__main__:INFO:Input of get_eID fn : NIFTY, pe,18Feb2021,15250
2021-02-12 10:59:13,818:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-12 10:59:15,069:__main__:INFO:Exchange Instrument ID : 47747, {'oty': ['CE', 'PE'], 'ss': ['39549', '47747']}
2021-02-12 10:59:15,071:__main__:INFO:Checking margin from user..
2021-02-12 10:59:15,073:__main__:INFO:Checking balance..
2021-02-12 10:59:17,444:__main__:INFO:Balance retreived success, available cash : 1000000000
2021-02-12 10:59:17,447:__main__:INFO: 
              net_cash - 1000000000,
              strikePrice - 15250,
              Nifty Spot - 15225.85,
              BankNifty Spot - None
              exchangeInstrumentID - [39549, 47747]
              
2021-02-12 10:59:17,449:__main__:INFO:All set from prepareVars func.. Giving a go for orders..
2021-02-12 10:59:17,451:__main__:INFO:required variables set-- ready to trigger orders at desired time
2021-02-12 11:00:00,407:__main__:INFO:Required Margin Available.. Taking positions...
2021-02-12 11:00:05,858:__main__:INFO:printing new_dictR value : [{'ordrtyp': 'Entry', 'ss': '39549', 'qq': 75, 'oo': 10024967, 'tt': 88.65}, {'ordrtyp': 'Entry', 'ss': '47747', 'qq': 75, 'oo': 10024966, 'tt': 114.5}]
2021-02-12 11:00:05,985:__main__:INFO:starting multi funcs with threaded timer...
2021-02-12 11:00:05,986:__main__:INFO:--- Entering SquareOffLogic Function after placing orders ---
2021-02-12 11:00:05,987:__main__:INFO:
 Entering runSqOffLogics func,
 	 This logic runs till the end of the script and 
              checks SL/TARGET/TIMEings 

2021-02-12 11:00:05,988:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:08,690:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   88.4   18.75  CE
1   Entry  47747  75  10024966  114.50  116.0 -112.50  PE 

2021-02-12 11:00:08,691:__main__:INFO:('12-02-2021 11:00:08', -93.75)
2021-02-12 11:00:10,701:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:13,301:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp    pnl oty
0   Entry  39549  75  10024967   88.65   89.0 -26.25  CE
1   Entry  47747  75  10024966  114.50  115.0 -37.50  PE 

2021-02-12 11:00:13,301:__main__:INFO:('12-02-2021 11:00:13', -63.75)
2021-02-12 11:00:15,317:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:17,231:__main__:INFO:Cur price of NIFTY is: 15234.85
2021-02-12 11:00:17,233:__main__:INFO:Points changed: 9.0
2021-02-12 11:00:17,234:__main__:INFO:repair running...
2021-02-12 11:00:17,985:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   89.85 -90.00  CE
1   Entry  47747  75  10024966  114.50  113.65  63.75  PE 

2021-02-12 11:00:17,986:__main__:INFO:('12-02-2021 11:00:17', -26.25)
2021-02-12 11:00:19,988:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:22,756:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp   pnl oty
0   Entry  39549  75  10024967   88.65   89.75 -82.5  CE
1   Entry  47747  75  10024966  114.50  113.50  75.0  PE 

2021-02-12 11:00:22,757:__main__:INFO:('12-02-2021 11:00:22', -7.5)
2021-02-12 11:00:24,763:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:27,283:__main__:INFO:Cur price of NIFTY is: 15235.25
2021-02-12 11:00:27,288:__main__:INFO:Points changed: 9.4
2021-02-12 11:00:27,290:__main__:INFO:repair running...
2021-02-12 11:00:27,376:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   89.55 -67.50  CE
1   Entry  47747  75  10024966  114.50  114.15  26.25  PE 

2021-02-12 11:00:27,378:__main__:INFO:('12-02-2021 11:00:27', -41.25)
2021-02-12 11:00:29,379:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:31,938:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   89.00 -26.25  CE
1   Entry  47747  75  10024966  114.50  114.55  -3.75  PE 

2021-02-12 11:00:31,939:__main__:INFO:('12-02-2021 11:00:31', -30.0)
2021-02-12 11:00:33,945:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:36,621:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp    pnl oty
0   Entry  39549  75  10024967   88.65   88.5  11.25  CE
1   Entry  47747  75  10024966  114.50  114.7 -15.00  PE 

2021-02-12 11:00:36,623:__main__:INFO:('12-02-2021 11:00:36', -3.75)
2021-02-12 11:00:37,322:__main__:INFO:Cur price of NIFTY is: 15233.4
2021-02-12 11:00:37,328:__main__:INFO:Points changed: 7.55
2021-02-12 11:00:37,329:__main__:INFO:repair running...
2021-02-12 11:00:38,640:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:41,230:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   88.95 -22.50  CE
1   Entry  47747  75  10024966  114.50  114.75 -18.75  PE 

2021-02-12 11:00:41,231:__main__:INFO:('12-02-2021 11:00:41', -41.25)
2021-02-12 11:00:43,236:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:45,944:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   88.50  11.25  CE
1   Entry  47747  75  10024966  114.50  115.05 -41.25  PE 

2021-02-12 11:00:45,944:__main__:INFO:('12-02-2021 11:00:45', -30.0)
2021-02-12 11:00:47,311:__main__:INFO:Cur price of NIFTY is: 15232.55
2021-02-12 11:00:47,315:__main__:INFO:Points changed: 6.7
2021-02-12 11:00:47,317:__main__:INFO:repair running...
2021-02-12 11:00:47,954:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:50,596:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   88.3   26.25  CE
1   Entry  47747  75  10024966  114.50  115.9 -105.00  PE 

2021-02-12 11:00:50,597:__main__:INFO:('12-02-2021 11:00:50', -78.75)
2021-02-12 11:00:52,606:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:55,125:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   88.05   45.00  CE
1   Entry  47747  75  10024966  114.50  115.85 -101.25  PE 

2021-02-12 11:00:55,126:__main__:INFO:('12-02-2021 11:00:55', -56.25)
2021-02-12 11:00:57,137:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:00:57,280:__main__:INFO:Cur price of NIFTY is: 15230.25
2021-02-12 11:00:57,284:__main__:INFO:Points changed: 4.4
2021-02-12 11:00:57,286:__main__:INFO:repair running...
2021-02-12 11:00:59,794:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.7   71.25  CE
1   Entry  47747  75  10024966  114.50  116.5 -150.00  PE 

2021-02-12 11:00:59,795:__main__:INFO:('12-02-2021 11:00:59', -78.75)
2021-02-12 11:01:01,807:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:04,425:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.70  146.25  CE
1   Entry  47747  75  10024966  114.50  116.95 -183.75  PE 

2021-02-12 11:01:04,426:__main__:INFO:('12-02-2021 11:01:04', -37.5)
2021-02-12 11:01:06,438:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:07,337:__main__:INFO:Cur price of NIFTY is: 15226.75
2021-02-12 11:01:07,339:__main__:INFO:Points changed: 0.9
2021-02-12 11:01:07,340:__main__:INFO:repair running...
2021-02-12 11:01:09,046:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.4  168.75  CE
1   Entry  47747  75  10024966  114.50  116.9 -180.00  PE 

2021-02-12 11:01:09,047:__main__:INFO:('12-02-2021 11:01:09', -11.25)
2021-02-12 11:01:11,061:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:13,655:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.80  138.75  CE
1   Entry  47747  75  10024966  114.50  117.35 -213.75  PE 

2021-02-12 11:01:13,657:__main__:INFO:('12-02-2021 11:01:13', -75.0)
2021-02-12 11:01:15,660:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:17,311:__main__:INFO:Cur price of NIFTY is: 15226.35
2021-02-12 11:01:17,316:__main__:INFO:Points changed: 0.5
2021-02-12 11:01:17,317:__main__:INFO:repair running...
2021-02-12 11:01:18,189:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.45  165.00  CE
1   Entry  47747  75  10024966  114.50  117.55 -228.75  PE 

2021-02-12 11:01:18,190:__main__:INFO:('12-02-2021 11:01:18', -63.75)
2021-02-12 11:01:20,192:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:22,760:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.10  116.25  CE
1   Entry  47747  75  10024966  114.50  117.15 -198.75  PE 

2021-02-12 11:01:22,761:__main__:INFO:('12-02-2021 11:01:22', -82.5)
2021-02-12 11:01:24,764:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:27,379:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.7  146.25  CE
1   Entry  47747  75  10024966  114.50  117.9 -255.00  PE 

2021-02-12 11:01:27,381:__main__:INFO:Cur price of NIFTY is: 15227.8
2021-02-12 11:01:27,382:__main__:INFO:('12-02-2021 11:01:27', -108.75)
2021-02-12 11:01:27,385:__main__:INFO:Points changed: 1.95
2021-02-12 11:01:27,388:__main__:INFO:repair running...
2021-02-12 11:01:29,390:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:31,984:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.9  131.25  CE
1   Entry  47747  75  10024966  114.50  118.0 -262.50  PE 

2021-02-12 11:01:31,985:__main__:INFO:('12-02-2021 11:01:31', -131.25)
2021-02-12 11:01:33,994:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:36,571:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   86.85  135.0  CE
1   Entry  47747  75  10024966  114.50  118.00 -262.5  PE 

2021-02-12 11:01:36,573:__main__:INFO:('12-02-2021 11:01:36', -127.5)
2021-02-12 11:01:37,318:__main__:INFO:Cur price of NIFTY is: 15226.95
2021-02-12 11:01:37,322:__main__:INFO:Points changed: 1.1
2021-02-12 11:01:37,324:__main__:INFO:repair running...
2021-02-12 11:01:38,586:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:41,236:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   86.85  135.0  CE
1   Entry  47747  75  10024966  114.50  118.00 -262.5  PE 

2021-02-12 11:01:41,237:__main__:INFO:('12-02-2021 11:01:41', -127.5)
2021-02-12 11:01:43,251:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:46,042:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.30  176.25  CE
1   Entry  47747  75  10024966  114.50  118.25 -281.25  PE 

2021-02-12 11:01:46,044:__main__:INFO:('12-02-2021 11:01:46', -105.0)
2021-02-12 11:01:47,531:__main__:INFO:Cur price of NIFTY is: 15225.4
2021-02-12 11:01:47,536:__main__:INFO:Points changed: -0.45
2021-02-12 11:01:47,538:__main__:INFO:repair running...
2021-02-12 11:01:48,055:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:51,012:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   85.75  217.5  CE
1   Entry  47747  75  10024966  114.50  119.20 -352.5  PE 

2021-02-12 11:01:51,012:__main__:INFO:('12-02-2021 11:01:51', -135.0)
2021-02-12 11:01:53,016:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:01:56,038:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   85.95  202.5  CE
1   Entry  47747  75  10024966  114.50  119.00 -337.5  PE 

2021-02-12 11:01:56,039:__main__:INFO:('12-02-2021 11:01:56', -135.0)
2021-02-12 11:01:57,474:__main__:INFO:Cur price of NIFTY is: 15223.95
2021-02-12 11:01:57,477:__main__:INFO:Points changed: -1.9
2021-02-12 11:01:57,477:__main__:INFO:repair running...
2021-02-12 11:01:58,048:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:00,946:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   86.25  180.0  CE
1   Entry  47747  75  10024966  114.50  118.90 -330.0  PE 

2021-02-12 11:02:00,947:__main__:INFO:('12-02-2021 11:02:00', -150.0)
2021-02-12 11:02:02,949:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:05,892:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.5  161.25  CE
1   Entry  47747  75  10024966  114.50  118.2 -277.50  PE 

2021-02-12 11:02:05,893:__main__:INFO:('12-02-2021 11:02:05', -116.25)
2021-02-12 11:02:07,492:__main__:INFO:Cur price of NIFTY is: 15224.55
2021-02-12 11:02:07,495:__main__:INFO:Points changed: -1.3
2021-02-12 11:02:07,496:__main__:INFO:repair running...
2021-02-12 11:02:07,895:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:10,840:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.2  108.75  CE
1   Entry  47747  75  10024966  114.50  117.9 -255.00  PE 

2021-02-12 11:02:10,841:__main__:INFO:('12-02-2021 11:02:10', -146.25)
2021-02-12 11:02:12,846:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:15,815:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp    pnl oty
0   Entry  39549  75  10024967   88.65   87.25  105.0  CE
1   Entry  47747  75  10024966  114.50  118.00 -262.5  PE 

2021-02-12 11:02:15,816:__main__:INFO:('12-02-2021 11:02:15', -157.5)
2021-02-12 11:02:17,472:__main__:INFO:Cur price of NIFTY is: 15227.15
2021-02-12 11:02:17,476:__main__:INFO:Points changed: 1.3
2021-02-12 11:02:17,477:__main__:INFO:repair running...
2021-02-12 11:02:17,827:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:20,745:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.0  123.75  CE
1   Entry  47747  75  10024966  114.50  118.0 -262.50  PE 

2021-02-12 11:02:20,746:__main__:INFO:('12-02-2021 11:02:20', -138.75)
2021-02-12 11:02:22,758:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:25,621:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.0  123.75  CE
1   Entry  47747  75  10024966  114.50  118.0 -262.50  PE 

2021-02-12 11:02:25,625:__main__:INFO:('12-02-2021 11:02:25', -138.75)
2021-02-12 11:02:27,618:__main__:INFO:Cur price of NIFTY is: 15226
2021-02-12 11:02:27,621:__main__:INFO:Points changed: 0.15
2021-02-12 11:02:27,622:__main__:INFO:repair running...
2021-02-12 11:02:27,632:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:30,546:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.10  116.25  CE
1   Entry  47747  75  10024966  114.50  117.75 -243.75  PE 

2021-02-12 11:02:30,548:__main__:INFO:('12-02-2021 11:02:30', -127.5)
2021-02-12 11:02:32,564:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:35,589:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.1  116.25  CE
1   Entry  47747  75  10024966  114.50  118.3 -285.00  PE 

2021-02-12 11:02:35,590:__main__:INFO:('12-02-2021 11:02:35', -168.75)
2021-02-12 11:02:37,515:__main__:INFO:Cur price of NIFTY is: 15227.25
2021-02-12 11:02:37,519:__main__:INFO:Points changed: 1.4
2021-02-12 11:02:37,520:__main__:INFO:repair running...
2021-02-12 11:02:37,592:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:40,508:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.15  112.50  CE
1   Entry  47747  75  10024966  114.50  118.05 -266.25  PE 

2021-02-12 11:02:40,509:__main__:INFO:('12-02-2021 11:02:40', -153.75)
2021-02-12 11:02:42,519:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:45,404:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.45   90.00  CE
1   Entry  47747  75  10024966  114.50  117.75 -243.75  PE 

2021-02-12 11:02:45,405:__main__:INFO:('12-02-2021 11:02:45', -153.75)
2021-02-12 11:02:47,406:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:47,516:__main__:INFO:Cur price of NIFTY is: 15226.4
2021-02-12 11:02:47,520:__main__:INFO:Points changed: 0.55
2021-02-12 11:02:47,523:__main__:INFO:repair running...
2021-02-12 11:02:50,241:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.20  108.75  CE
1   Entry  47747  75  10024966  114.50  118.25 -281.25  PE 

2021-02-12 11:02:50,242:__main__:INFO:('12-02-2021 11:02:50', -172.5)
2021-02-12 11:02:52,245:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:55,157:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.2  108.75  CE
1   Entry  47747  75  10024966  114.50  118.9 -330.00  PE 

2021-02-12 11:02:55,158:__main__:INFO:('12-02-2021 11:02:55', -221.25)
2021-02-12 11:02:57,170:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:02:57,506:__main__:INFO:Cur price of NIFTY is: 15226.75
2021-02-12 11:02:57,511:__main__:INFO:Points changed: 0.9
2021-02-12 11:02:57,513:__main__:INFO:repair running...
2021-02-12 11:03:00,113:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   87.0  123.75  CE
1   Entry  47747  75  10024966  114.50  119.0 -337.50  PE 

2021-02-12 11:03:00,114:__main__:INFO:('12-02-2021 11:03:00', -213.75)
2021-02-12 11:03:02,117:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:05,169:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.5  161.25  CE
1   Entry  47747  75  10024966  114.50  120.0 -412.50  PE 

2021-02-12 11:03:05,171:__main__:INFO:('12-02-2021 11:03:05', -251.25)
2021-02-12 11:03:07,188:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:07,526:__main__:INFO:Cur price of NIFTY is: 15223.9
2021-02-12 11:03:07,530:__main__:INFO:Points changed: -1.95
2021-02-12 11:03:07,532:__main__:INFO:repair running...
2021-02-12 11:03:10,094:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.1  191.25  CE
1   Entry  47747  75  10024966  114.50  120.1 -420.00  PE 

2021-02-12 11:03:10,095:__main__:INFO:('12-02-2021 11:03:10', -228.75)
2021-02-12 11:03:12,098:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:14,957:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt    ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.4  168.75  CE
1   Entry  47747  75  10024966  114.50  120.0 -412.50  PE 

2021-02-12 11:03:14,958:__main__:INFO:('12-02-2021 11:03:14', -243.75)
2021-02-12 11:03:16,971:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:17,627:__main__:INFO:Cur price of NIFTY is: 15222.4
2021-02-12 11:03:17,632:__main__:INFO:Points changed: -3.45
2021-02-12 11:03:17,633:__main__:INFO:repair running...
2021-02-12 11:03:20,561:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.55  157.50  CE
1   Entry  47747  75  10024966  114.50  120.25 -431.25  PE 

2021-02-12 11:03:20,562:__main__:INFO:('12-02-2021 11:03:20', -273.75)
2021-02-12 11:03:22,571:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:25,634:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   86.05  195.00  CE
1   Entry  47747  75  10024966  114.50  120.95 -483.75  PE 

2021-02-12 11:03:25,635:__main__:INFO:('12-02-2021 11:03:25', -288.75)
2021-02-12 11:03:27,645:__main__:INFO:Cur price of NIFTY is: 15222.2
2021-02-12 11:03:27,645:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:27,648:__main__:INFO:Points changed: -3.65
2021-02-12 11:03:27,658:__main__:INFO:repair running...
2021-02-12 11:03:30,783:__main__:INFO: DF is : 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   85.75  217.50  CE
1   Entry  47747  75  10024966  114.50  120.75 -468.75  PE 

2021-02-12 11:03:30,785:__main__:INFO:('12-02-2021 11:03:30', -251.25)
2021-02-12 11:03:32,795:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:34,237:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:34,240:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:35,852:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:35,854:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:37,357:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:37,359:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:37,636:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 144, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:38,977:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:38,979:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:40,458:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:40,459:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:41,933:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:41,936:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:43,410:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:43,412:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:44,941:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:44,943:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:46,435:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:46,437:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:47,627:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 144, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:47,957:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:47,959:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:49,354:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:49,355:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:50,875:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:50,877:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:52,375:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:52,377:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:53,925:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:53,928:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:55,469:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:55,471:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:57,044:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:57,047:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:03:57,651:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 144, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:58,509:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:03:58,511:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:00,014:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:00,016:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:01,453:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:01,456:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:02,920:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:02,922:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:04,419:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:04,421:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:05,873:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:05,876:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:07,388:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:07,391:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:07,684:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 144, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:08,870:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:08,873:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:10,376:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:10,379:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:11,913:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:11,915:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:13,477:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:13,478:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:14,966:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:14,969:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:16,424:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:16,427:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:17,732:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 144, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:18,004:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:18,007:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:19,558:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:19,562:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:21,069:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:21,071:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:22,627:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:22,630:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:24,084:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:24,086:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:25,587:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:25,589:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:27,010:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 463, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-12 11:04:27,011:__main__:INFO:Checking CurPnL for this strategy..
2021-02-12 11:04:27,415:__main__:INFO:Strategy2 Summary: 
   ordrtyp     ss  qq        oo      tt     ltp     pnl oty
0   Entry  39549  75  10024967   88.65   85.75  217.50  CE
1   Entry  47747  75  10024966  114.50  120.75 -468.75  PE
2021-02-12 11:04:27,416:__main__:INFO:Dumping the PnL list to excel sheet..
2021-02-12 11:04:27,514:__main__:INFO:in finally block.. Closing multi threaded func if running..
2021-02-12 11:04:27,516:__main__:INFO:-- Script Ended --
2021-02-12 11:04:27,517:__main__:INFO:-- --------------------------------------------- --
2021-02-12 11:04:27,633:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token_run3.py", line 144, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
