2021-02-15 09:58:58,253:__main__:INFO:Creating token file
2021-02-15 09:58:59,380:__main__:INFO:Valid User.
2021-02-15 09:58:59,380:__main__:INFO:Calculating everything before executing orders..
2021-02-15 09:58:59,395:__main__:INFO:Calculating weekly and monthly expiry dates..
2021-02-15 09:58:59,395:__main__:INFO:weekly expiry is : 18Feb2021, monthly expiry is: 25Feb2021
2021-02-15 09:59:00,389:__main__:INFO:StrikePrice computed as : 15300
2021-02-15 09:59:00,389:__main__:INFO:Input of get_eID fn : NIFTY, ce,18Feb2021,15300
2021-02-15 09:59:00,389:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-15 09:59:01,422:__main__:INFO:Exchange Instrument ID : 39842, 39842,  {'oty': ['CE'], 'ss': ['39842'], 'nn': [39842]}
2021-02-15 09:59:01,424:__main__:INFO:Input of get_eID fn : NIFTY, pe,18Feb2021,15300
2021-02-15 09:59:01,425:__main__:INFO:Today is not Thursday. Hence straddle
2021-02-15 09:59:02,481:__main__:INFO:Exchange Instrument ID : 47749, 47749,  {'oty': ['CE', 'PE'], 'ss': ['39842', '47749'], 'nn': [39842, 47749]}
2021-02-15 09:59:02,483:__main__:INFO:Checking margin from user..
2021-02-15 09:59:02,483:__main__:INFO:Checking balance..
2021-02-15 09:59:06,909:__main__:INFO:Balance retreived success, available cash : 1000000000
2021-02-15 09:59:06,909:__main__:INFO: 
              net_cash - 1000000000,
              strikePrice - 15300,
              Nifty Spot - 15295.15,
              BankNifty Spot - None
              exchangeInstrumentID - [39842, 47749]
              
2021-02-15 09:59:06,909:__main__:INFO:All set from prepareVars func.. Giving a go for orders..
2021-02-15 09:59:06,909:__main__:INFO:required variables set-- ready to trigger orders at desired time
2021-02-15 10:00:00,353:__main__:INFO:Required Margin Available.. Taking positions...
2021-02-15 10:00:04,647:__main__:INFO:printing new_dictR value : [{'ordrtyp': 'Entry', 'ss': '47749', 'qq': 75, 'oo': 10025849, 'tt': 88.6}, {'ordrtyp': 'Entry', 'ss': '39842', 'qq': 75, 'oo': 10025850, 'tt': 65.45}]
2021-02-15 10:00:04,762:__main__:INFO:starting multi funcs with threaded timer...
2021-02-15 10:00:04,764:__main__:INFO:--- Entering SquareOffLogic Function after placing orders ---
2021-02-15 10:00:04,764:__main__:INFO:
 Entering runSqOffLogics func,
 	 This logic runs till the end of the script and 
              checks SL/TARGET/TIMEings 

2021-02-15 10:00:04,764:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:07,048:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.60   0.0  PE
1   Entry  39842  39842  75  10025850  65.45  65.65 -15.0  CE 

2021-02-15 10:00:07,048:__main__:INFO:('15-02-2021 10:00:07', -15.0)
2021-02-15 10:00:09,062:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:11,301:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.35  18.75  PE
1   Entry  39842  39842  75  10025850  65.45  65.95 -37.50  CE 

2021-02-15 10:00:11,302:__main__:INFO:('15-02-2021 10:00:11', -18.75)
2021-02-15 10:00:13,305:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:15,289:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.45  11.25  PE
1   Entry  39842  39842  75  10025850  65.45  65.85 -30.00  CE 

2021-02-15 10:00:15,289:__main__:INFO:('15-02-2021 10:00:15', -18.75)
2021-02-15 10:00:15,712:__main__:INFO:Cur price of NIFTY is: 15290.9
2021-02-15 10:00:15,717:__main__:INFO:Points changed: -4.25
2021-02-15 10:00:15,719:__main__:INFO:repair running...
2021-02-15 10:00:17,296:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:19,271:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  87.7  67.50  PE
1   Entry  39842  39842  75  10025850  65.45  66.5 -78.75  CE 

2021-02-15 10:00:19,271:__main__:INFO:('15-02-2021 10:00:19', -11.25)
2021-02-15 10:00:21,284:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:23,230:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  87.90  52.5  PE
1   Entry  39842  39842  75  10025850  65.45  66.15 -52.5  CE 

2021-02-15 10:00:23,230:__main__:INFO:('15-02-2021 10:00:23', -0.0)
2021-02-15 10:00:23,230:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:25,144:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.25  26.25  PE
1   Entry  39842  39842  75  10025850  65.45  66.15 -52.50  CE 

2021-02-15 10:00:25,145:__main__:INFO:('15-02-2021 10:00:25', -26.25)
2021-02-15 10:00:25,724:__main__:INFO:Cur price of NIFTY is: 15291.95
2021-02-15 10:00:25,724:__main__:INFO:Points changed: -3.2
2021-02-15 10:00:25,724:__main__:INFO:repair running...
2021-02-15 10:00:27,153:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:29,091:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  87.95  48.75  PE
1   Entry  39842  39842  75  10025850  65.45  66.20 -56.25  CE 

2021-02-15 10:00:29,092:__main__:INFO:('15-02-2021 10:00:29', -7.5)
2021-02-15 10:00:31,109:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:33,039:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.30  22.5  PE
1   Entry  39842  39842  75  10025850  65.45  66.25 -60.0  CE 

2021-02-15 10:00:33,040:__main__:INFO:('15-02-2021 10:00:33', -37.5)
2021-02-15 10:00:35,053:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:35,741:__main__:INFO:Cur price of NIFTY is: 15289.75
2021-02-15 10:00:35,746:__main__:INFO:Points changed: -5.4
2021-02-15 10:00:35,748:__main__:INFO:repair running...
2021-02-15 10:00:36,949:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.8 -15.00  PE
1   Entry  39842  39842  75  10025850  65.45  65.8 -26.25  CE 

2021-02-15 10:00:36,950:__main__:INFO:('15-02-2021 10:00:36', -41.25)
2021-02-15 10:00:38,952:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:40,914:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.7  -7.50  PE
1   Entry  39842  39842  75  10025850  65.45  66.0 -41.25  CE 

2021-02-15 10:00:40,915:__main__:INFO:('15-02-2021 10:00:40', -48.75)
2021-02-15 10:00:42,929:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:44,960:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.05 -33.75  PE
1   Entry  39842  39842  75  10025850  65.45  65.30  11.25  CE 

2021-02-15 10:00:44,961:__main__:INFO:('15-02-2021 10:00:44', -22.5)
2021-02-15 10:00:45,746:__main__:INFO:Cur price of NIFTY is: 15289.1
2021-02-15 10:00:45,748:__main__:INFO:Points changed: -6.05
2021-02-15 10:00:45,749:__main__:INFO:repair running...
2021-02-15 10:00:46,974:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:48,984:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.50 -67.5  PE
1   Entry  39842  39842  75  10025850  65.45  65.25  15.0  CE 

2021-02-15 10:00:48,985:__main__:INFO:('15-02-2021 10:00:48', -52.5)
2021-02-15 10:00:50,997:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:52,973:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.0 -105.00  PE
1   Entry  39842  39842  75  10025850  65.45  64.7   56.25  CE 

2021-02-15 10:00:52,974:__main__:INFO:('15-02-2021 10:00:52', -48.75)
2021-02-15 10:00:54,978:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:00:55,802:__main__:INFO:Cur price of NIFTY is: 15288.2
2021-02-15 10:00:55,806:__main__:INFO:Points changed: -6.95
2021-02-15 10:00:55,807:__main__:INFO:repair running...
2021-02-15 10:00:56,908:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.60 -75.0  PE
1   Entry  39842  39842  75  10025850  65.45  65.05  30.0  CE 

2021-02-15 10:00:56,909:__main__:INFO:('15-02-2021 10:00:56', -45.0)
2021-02-15 10:00:58,924:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:00,877:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.95 -26.25  PE
1   Entry  39842  39842  75  10025850  65.45  65.20  18.75  CE 

2021-02-15 10:01:00,878:__main__:INFO:('15-02-2021 10:01:00', -7.5)
2021-02-15 10:01:02,890:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:04,930:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.25 -48.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.65  60.00  CE 

2021-02-15 10:01:04,930:__main__:INFO:('15-02-2021 10:01:04', 11.25)
2021-02-15 10:01:05,755:__main__:INFO:Cur price of NIFTY is: 15286.05
2021-02-15 10:01:05,761:__main__:INFO:Points changed: -9.1
2021-02-15 10:01:05,762:__main__:INFO:repair running...
2021-02-15 10:01:06,944:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:08,893:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.00 -30.0  PE
1   Entry  39842  39842  75  10025850  65.45  64.45  75.0  CE 

2021-02-15 10:01:08,895:__main__:INFO:('15-02-2021 10:01:08', 45.0)
2021-02-15 10:01:10,906:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:12,863:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.45 -63.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.70  56.25  CE 

2021-02-15 10:01:12,864:__main__:INFO:('15-02-2021 10:01:12', -7.5)
2021-02-15 10:01:14,872:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:15,746:__main__:INFO:Cur price of NIFTY is: 15286.5
2021-02-15 10:01:15,748:__main__:INFO:Points changed: -8.65
2021-02-15 10:01:15,749:__main__:INFO:repair running...
2021-02-15 10:01:16,776:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.1 -112.50  PE
1   Entry  39842  39842  75  10025850  65.45  64.2   93.75  CE 

2021-02-15 10:01:16,777:__main__:INFO:('15-02-2021 10:01:16', -18.75)
2021-02-15 10:01:18,786:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:20,767:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.65 -78.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.35  82.50  CE 

2021-02-15 10:01:20,769:__main__:INFO:('15-02-2021 10:01:20', 3.75)
2021-02-15 10:01:22,773:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:24,735:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.95 -101.25  PE
1   Entry  39842  39842  75  10025850  65.45  64.35   82.50  CE 

2021-02-15 10:01:24,737:__main__:INFO:('15-02-2021 10:01:24', -18.75)
2021-02-15 10:01:25,742:__main__:INFO:Cur price of NIFTY is: 15286.4
2021-02-15 10:01:25,744:__main__:INFO:Points changed: -8.75
2021-02-15 10:01:25,745:__main__:INFO:repair running...
2021-02-15 10:01:26,739:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:28,699:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.35  18.75  PE
1   Entry  39842  39842  75  10025850  65.45  65.65 -15.00  CE 

2021-02-15 10:01:28,700:__main__:INFO:('15-02-2021 10:01:28', 3.75)
2021-02-15 10:01:30,709:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:32,615:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.4  15.00  PE
1   Entry  39842  39842  75  10025850  65.45  65.4   3.75  CE 

2021-02-15 10:01:32,615:__main__:INFO:('15-02-2021 10:01:32', 18.75)
2021-02-15 10:01:34,617:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:35,816:__main__:INFO:Cur price of NIFTY is: 15288.4
2021-02-15 10:01:35,820:__main__:INFO:Points changed: -6.75
2021-02-15 10:01:35,820:__main__:INFO:repair running...
2021-02-15 10:01:36,559:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.15 -41.25  PE
1   Entry  39842  39842  75  10025850  65.45  65.40   3.75  CE 

2021-02-15 10:01:36,559:__main__:INFO:('15-02-2021 10:01:36', -37.5)
2021-02-15 10:01:38,565:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:40,479:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.3 -52.50  PE
1   Entry  39842  39842  75  10025850  65.45  64.9  41.25  CE 

2021-02-15 10:01:40,480:__main__:INFO:('15-02-2021 10:01:40', -11.25)
2021-02-15 10:01:42,493:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:44,423:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.6 -75.00  PE
1   Entry  39842  39842  75  10025850  65.45  64.9  41.25  CE 

2021-02-15 10:01:44,424:__main__:INFO:('15-02-2021 10:01:44', -33.75)
2021-02-15 10:01:45,779:__main__:INFO:Cur price of NIFTY is: 15289.4
2021-02-15 10:01:45,782:__main__:INFO:Points changed: -5.75
2021-02-15 10:01:45,783:__main__:INFO:repair running...
2021-02-15 10:01:46,438:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:48,322:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.8 -15.00  PE
1   Entry  39842  39842  75  10025850  65.45  65.5  -3.75  CE 

2021-02-15 10:01:48,324:__main__:INFO:('15-02-2021 10:01:48', -18.75)
2021-02-15 10:01:50,330:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:52,413:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.95 -26.25  PE
1   Entry  39842  39842  75  10025850  65.45  65.50  -3.75  CE 

2021-02-15 10:01:52,414:__main__:INFO:('15-02-2021 10:01:52', -30.0)
2021-02-15 10:01:54,431:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:01:55,821:__main__:INFO:Cur price of NIFTY is: 15289.4
2021-02-15 10:01:55,825:__main__:INFO:Points changed: -5.75
2021-02-15 10:01:55,827:__main__:INFO:repair running...
2021-02-15 10:01:56,383:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.95 -26.25  PE
1   Entry  39842  39842  75  10025850  65.45  65.50  -3.75  CE 

2021-02-15 10:01:56,384:__main__:INFO:('15-02-2021 10:01:56', -30.0)
2021-02-15 10:01:58,396:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:00,295:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.00 -30.0  PE
1   Entry  39842  39842  75  10025850  65.45  65.25  15.0  CE 

2021-02-15 10:02:00,296:__main__:INFO:('15-02-2021 10:02:00', -15.0)
2021-02-15 10:02:02,306:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:04,243:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.00 -30.0  PE
1   Entry  39842  39842  75  10025850  65.45  65.65 -15.0  CE 

2021-02-15 10:02:04,244:__main__:INFO:('15-02-2021 10:02:04', -45.0)
2021-02-15 10:02:05,833:__main__:INFO:Cur price of NIFTY is: 15289.05
2021-02-15 10:02:05,837:__main__:INFO:Points changed: -6.1
2021-02-15 10:02:05,839:__main__:INFO:repair running...
2021-02-15 10:02:06,252:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:08,230:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.05 -33.75  PE
1   Entry  39842  39842  75  10025850  65.45  65.85 -30.00  CE 

2021-02-15 10:02:08,231:__main__:INFO:('15-02-2021 10:02:08', -63.75)
2021-02-15 10:02:10,239:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:12,112:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.85 -18.75  PE
1   Entry  39842  39842  75  10025850  65.45  65.50  -3.75  CE 

2021-02-15 10:02:12,113:__main__:INFO:('15-02-2021 10:02:12', -22.5)
2021-02-15 10:02:14,125:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:15,824:__main__:INFO:Cur price of NIFTY is: 15289.55
2021-02-15 10:02:15,829:__main__:INFO:Points changed: -5.6
2021-02-15 10:02:15,830:__main__:INFO:repair running...
2021-02-15 10:02:16,101:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.85 -18.75  PE
1   Entry  39842  39842  75  10025850  65.45  65.75 -22.50  CE 

2021-02-15 10:02:16,103:__main__:INFO:('15-02-2021 10:02:16', -41.25)
2021-02-15 10:02:18,109:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:20,049:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.95 -26.25  PE
1   Entry  39842  39842  75  10025850  65.45  65.35   7.50  CE 

2021-02-15 10:02:20,050:__main__:INFO:('15-02-2021 10:02:20', -18.75)
2021-02-15 10:02:22,056:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:23,950:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  88.80 -15.0  PE
1   Entry  39842  39842  75  10025850  65.45  65.45   0.0  CE 

2021-02-15 10:02:23,951:__main__:INFO:('15-02-2021 10:02:23', -15.0)
2021-02-15 10:02:25,817:__main__:INFO:Cur price of NIFTY is: 15288.9
2021-02-15 10:02:25,820:__main__:INFO:Points changed: -6.25
2021-02-15 10:02:25,821:__main__:INFO:repair running...
2021-02-15 10:02:25,967:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:27,891:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.20 -45.0  PE
1   Entry  39842  39842  75  10025850  65.45  65.25  15.0  CE 

2021-02-15 10:02:27,891:__main__:INFO:('15-02-2021 10:02:27', -30.0)
2021-02-15 10:02:29,892:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:31,861:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.4 -60.00  PE
1   Entry  39842  39842  75  10025850  65.45  65.0  33.75  CE 

2021-02-15 10:02:31,862:__main__:INFO:('15-02-2021 10:02:31', -26.25)
2021-02-15 10:02:33,865:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:35,807:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.40 -60.0  PE
1   Entry  39842  39842  75  10025850  65.45  65.25  15.0  CE 

2021-02-15 10:02:35,808:__main__:INFO:('15-02-2021 10:02:35', -45.0)
2021-02-15 10:02:35,855:__main__:INFO:Cur price of NIFTY is: 15287.1
2021-02-15 10:02:35,857:__main__:INFO:Points changed: -8.05
2021-02-15 10:02:35,858:__main__:INFO:repair running...
2021-02-15 10:02:37,818:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:39,726:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.40 -60.0  PE
1   Entry  39842  39842  75  10025850  65.45  65.45   0.0  CE 

2021-02-15 10:02:39,727:__main__:INFO:('15-02-2021 10:02:39', -60.0)
2021-02-15 10:02:41,741:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:43,745:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.55 -71.25  PE
1   Entry  39842  39842  75  10025850  65.45  65.35   7.50  CE 

2021-02-15 10:02:43,746:__main__:INFO:('15-02-2021 10:02:43', -63.75)
2021-02-15 10:02:45,757:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:45,913:__main__:INFO:Cur price of NIFTY is: 15288.4
2021-02-15 10:02:45,918:__main__:INFO:Points changed: -6.75
2021-02-15 10:02:45,921:__main__:INFO:repair running...
2021-02-15 10:02:47,677:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.75 -86.25  PE
1   Entry  39842  39842  75  10025850  65.45  65.10  26.25  CE 

2021-02-15 10:02:47,678:__main__:INFO:('15-02-2021 10:02:47', -60.0)
2021-02-15 10:02:49,695:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:51,722:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp   pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.20 -45.0  PE
1   Entry  39842  39842  75  10025850  65.45  65.25  15.0  CE 

2021-02-15 10:02:51,723:__main__:INFO:('15-02-2021 10:02:51', -30.0)
2021-02-15 10:02:53,737:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:55,678:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.65 -78.75  PE
1   Entry  39842  39842  75  10025850  65.45  65.40   3.75  CE 

2021-02-15 10:02:55,679:__main__:INFO:('15-02-2021 10:02:55', -75.0)
2021-02-15 10:02:55,894:__main__:INFO:Cur price of NIFTY is: 15287
2021-02-15 10:02:55,897:__main__:INFO:Points changed: -8.15
2021-02-15 10:02:55,898:__main__:INFO:repair running...
2021-02-15 10:02:57,689:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:02:59,671:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.0 -105.00  PE
1   Entry  39842  39842  75  10025850  65.45  65.3   11.25  CE 

2021-02-15 10:02:59,672:__main__:INFO:('15-02-2021 10:02:59', -93.75)
2021-02-15 10:03:01,688:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:03,574:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.8 -90.00  PE
1   Entry  39842  39842  75  10025850  65.45  65.3  11.25  CE 

2021-02-15 10:03:03,575:__main__:INFO:('15-02-2021 10:03:03', -78.75)
2021-02-15 10:03:05,577:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:05,894:__main__:INFO:Cur price of NIFTY is: 15285.55
2021-02-15 10:03:05,896:__main__:INFO:Points changed: -9.6
2021-02-15 10:03:05,897:__main__:INFO:repair running...
2021-02-15 10:03:07,571:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.05 -108.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.90   41.25  CE 

2021-02-15 10:03:07,572:__main__:INFO:('15-02-2021 10:03:07', -67.5)
2021-02-15 10:03:09,588:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:11,568:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.25 -123.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.65   60.00  CE 

2021-02-15 10:03:11,569:__main__:INFO:('15-02-2021 10:03:11', -63.75)
2021-02-15 10:03:13,575:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:15,581:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.65 -153.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.95   37.50  CE 

2021-02-15 10:03:15,583:__main__:INFO:('15-02-2021 10:03:15', -116.25)
2021-02-15 10:03:15,964:__main__:INFO:Cur price of NIFTY is: 15286.95
2021-02-15 10:03:15,968:__main__:INFO:Points changed: -8.2
2021-02-15 10:03:15,970:__main__:INFO:repair running...
2021-02-15 10:03:17,593:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:19,597:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.45 -138.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.75   52.50  CE 

2021-02-15 10:03:19,598:__main__:INFO:('15-02-2021 10:03:19', -86.25)
2021-02-15 10:03:21,609:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:23,693:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.65 -153.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.70   56.25  CE 

2021-02-15 10:03:23,694:__main__:INFO:('15-02-2021 10:03:23', -97.5)
2021-02-15 10:03:25,707:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:25,987:__main__:INFO:Cur price of NIFTY is: 15283.95
2021-02-15 10:03:25,990:__main__:INFO:Points changed: -11.2
2021-02-15 10:03:25,991:__main__:INFO:repair running...
2021-02-15 10:03:27,747:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.95 -101.25  PE
1   Entry  39842  39842  75  10025850  65.45  65.00   33.75  CE 

2021-02-15 10:03:27,749:__main__:INFO:('15-02-2021 10:03:27', -67.5)
2021-02-15 10:03:29,767:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:31,791:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.9 -97.50  PE
1   Entry  39842  39842  75  10025850  65.45  64.9  41.25  CE 

2021-02-15 10:03:31,791:__main__:INFO:('15-02-2021 10:03:31', -56.25)
2021-02-15 10:03:33,795:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:35,813:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.95 -101.25  PE
1   Entry  39842  39842  75  10025850  65.45  64.95   37.50  CE 

2021-02-15 10:03:35,814:__main__:INFO:('15-02-2021 10:03:35', -63.75)
2021-02-15 10:03:35,988:__main__:INFO:Cur price of NIFTY is: 15284.75
2021-02-15 10:03:35,993:__main__:INFO:Points changed: -10.4
2021-02-15 10:03:35,995:__main__:INFO:repair running...
2021-02-15 10:03:37,824:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:39,774:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.95 -176.25  PE
1   Entry  39842  39842  75  10025850  65.45  64.10  101.25  CE 

2021-02-15 10:03:39,775:__main__:INFO:('15-02-2021 10:03:39', -75.0)
2021-02-15 10:03:41,782:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:43,840:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  92.00 -255.0  PE
1   Entry  39842  39842  75  10025850  65.45  63.55  142.5  CE 

2021-02-15 10:03:43,841:__main__:INFO:('15-02-2021 10:03:43', -112.5)
2021-02-15 10:03:45,844:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:45,977:__main__:INFO:Cur price of NIFTY is: 15282.5
2021-02-15 10:03:45,982:__main__:INFO:Points changed: -12.65
2021-02-15 10:03:45,983:__main__:INFO:repair running...
2021-02-15 10:03:47,897:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.85 -243.75  PE
1   Entry  39842  39842  75  10025850  65.45  63.50  146.25  CE 

2021-02-15 10:03:47,898:__main__:INFO:('15-02-2021 10:03:47', -97.5)
2021-02-15 10:03:49,910:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:52,107:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  92.35 -281.25  PE
1   Entry  39842  39842  75  10025850  65.45  63.10  176.25  CE 

2021-02-15 10:03:52,108:__main__:INFO:('15-02-2021 10:03:52', -105.0)
2021-02-15 10:03:54,114:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:03:56,022:__main__:INFO:Cur price of NIFTY is: 15280.6
2021-02-15 10:03:56,026:__main__:INFO:Points changed: -14.55
2021-02-15 10:03:56,027:__main__:INFO:repair running...
2021-02-15 10:03:56,081:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  92.0 -255.00  PE
1   Entry  39842  39842  75  10025850  65.45  62.9  191.25  CE 

2021-02-15 10:03:56,081:__main__:INFO:('15-02-2021 10:03:56', -63.75)
2021-02-15 10:03:58,088:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:00,150:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  92.85 -318.75  PE
1   Entry  39842  39842  75  10025850  65.45  62.30  236.25  CE 

2021-02-15 10:04:00,152:__main__:INFO:('15-02-2021 10:04:00', -82.5)
2021-02-15 10:04:02,166:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:04,188:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.20 -195.0  PE
1   Entry  39842  39842  75  10025850  65.45  63.45  150.0  CE 

2021-02-15 10:04:04,189:__main__:INFO:('15-02-2021 10:04:04', -45.0)
2021-02-15 10:04:06,001:__main__:INFO:Cur price of NIFTY is: 15279.55
2021-02-15 10:04:06,001:__main__:INFO:Points changed: -15.6
2021-02-15 10:04:06,001:__main__:INFO:repair running...
2021-02-15 10:04:06,203:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:08,322:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.90 -172.5  PE
1   Entry  39842  39842  75  10025850  65.45  63.25  165.0  CE 

2021-02-15 10:04:08,322:__main__:INFO:('15-02-2021 10:04:08', -7.5)
2021-02-15 10:04:10,327:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:12,298:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.9 -172.50  PE
1   Entry  39842  39842  75  10025850  65.45  64.0  108.75  CE 

2021-02-15 10:04:12,298:__main__:INFO:('15-02-2021 10:04:12', -63.75)
2021-02-15 10:04:14,305:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:16,018:__main__:INFO:Cur price of NIFTY is: 15280.7
2021-02-15 10:04:16,023:__main__:INFO:Points changed: -14.45
2021-02-15 10:04:16,024:__main__:INFO:repair running...
2021-02-15 10:04:16,406:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.05 -183.75  PE
1   Entry  39842  39842  75  10025850  65.45  63.45  150.00  CE 

2021-02-15 10:04:16,407:__main__:INFO:('15-02-2021 10:04:16', -33.75)
2021-02-15 10:04:18,409:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:20,531:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.75 -161.25  PE
1   Entry  39842  39842  75  10025850  65.45  63.45  150.00  CE 

2021-02-15 10:04:20,532:__main__:INFO:('15-02-2021 10:04:20', -11.25)
2021-02-15 10:04:22,546:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:24,538:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.65 -153.75  PE
1   Entry  39842  39842  75  10025850  65.45  63.65  135.00  CE 

2021-02-15 10:04:24,539:__main__:INFO:('15-02-2021 10:04:24', -18.75)
2021-02-15 10:04:26,042:__main__:INFO:Cur price of NIFTY is: 15281.75
2021-02-15 10:04:26,044:__main__:INFO:Points changed: -13.4
2021-02-15 10:04:26,045:__main__:INFO:repair running...
2021-02-15 10:04:26,541:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:28,542:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.4 -135.00  PE
1   Entry  39842  39842  75  10025850  65.45  64.0  108.75  CE 

2021-02-15 10:04:28,543:__main__:INFO:('15-02-2021 10:04:28', -26.25)
2021-02-15 10:04:30,552:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:32,566:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.05 -108.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.05  105.00  CE 

2021-02-15 10:04:32,566:__main__:INFO:('15-02-2021 10:04:32', -3.75)
2021-02-15 10:04:34,572:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:35,960:__main__:INFO:Cur price of NIFTY is: 15282.25
2021-02-15 10:04:35,976:__main__:INFO:Points changed: -12.9
2021-02-15 10:04:35,976:__main__:INFO:repair running...
2021-02-15 10:04:36,593:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.25 -123.75  PE
1   Entry  39842  39842  75  10025850  65.45  64.00  108.75  CE 

2021-02-15 10:04:36,593:__main__:INFO:('15-02-2021 10:04:36', -15.0)
2021-02-15 10:04:38,603:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:40,646:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.8 -165.00  PE
1   Entry  39842  39842  75  10025850  65.45  63.7  131.25  CE 

2021-02-15 10:04:40,647:__main__:INFO:('15-02-2021 10:04:40', -33.75)
2021-02-15 10:04:42,651:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:44,743:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.60 -150.0  PE
1   Entry  39842  39842  75  10025850  65.45  63.85  120.0  CE 

2021-02-15 10:04:44,745:__main__:INFO:('15-02-2021 10:04:44', -30.0)
2021-02-15 10:04:46,057:__main__:INFO:Cur price of NIFTY is: 15284.2
2021-02-15 10:04:46,062:__main__:INFO:Points changed: -10.95
2021-02-15 10:04:46,064:__main__:INFO:repair running...
2021-02-15 10:04:46,756:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:48,799:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.40 -135.0  PE
1   Entry  39842  39842  75  10025850  65.45  63.95  112.5  CE 

2021-02-15 10:04:48,800:__main__:INFO:('15-02-2021 10:04:48', -22.5)
2021-02-15 10:04:50,814:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:53,086:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.30 -127.5  PE
1   Entry  39842  39842  75  10025850  65.45  64.25   90.0  CE 

2021-02-15 10:04:53,086:__main__:INFO:('15-02-2021 10:04:53', -37.5)
2021-02-15 10:04:55,087:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:04:55,952:__main__:INFO:Cur price of NIFTY is: 15284.1
2021-02-15 10:04:55,952:__main__:INFO:Points changed: -11.05
2021-02-15 10:04:55,952:__main__:INFO:repair running...
2021-02-15 10:04:56,998:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.1 -112.50  PE
1   Entry  39842  39842  75  10025850  65.45  64.5   71.25  CE 

2021-02-15 10:04:56,998:__main__:INFO:('15-02-2021 10:04:56', -41.25)
2021-02-15 10:04:59,004:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:01,089:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.6 -75.00  PE
1   Entry  39842  39842  75  10025850  65.45  64.4  78.75  CE 

2021-02-15 10:05:01,105:__main__:INFO:('15-02-2021 10:05:01', 3.75)
2021-02-15 10:05:03,120:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:05,105:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.55 -71.25  PE
1   Entry  39842  39842  75  10025850  65.45  64.80  48.75  CE 

2021-02-15 10:05:05,105:__main__:INFO:('15-02-2021 10:05:05', -22.5)
2021-02-15 10:05:06,034:__main__:INFO:Cur price of NIFTY is: 15284.05
2021-02-15 10:05:06,034:__main__:INFO:Points changed: -11.1
2021-02-15 10:05:06,034:__main__:INFO:repair running...
2021-02-15 10:05:07,117:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:09,179:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  89.95 -101.25  PE
1   Entry  39842  39842  75  10025850  65.45  64.55   67.50  CE 

2021-02-15 10:05:09,179:__main__:INFO:('15-02-2021 10:05:09', -33.75)
2021-02-15 10:05:11,180:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:13,098:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.0 -105.00  PE
1   Entry  39842  39842  75  10025850  65.45  64.4   78.75  CE 

2021-02-15 10:05:13,098:__main__:INFO:('15-02-2021 10:05:13', -26.25)
2021-02-15 10:05:15,121:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:16,082:__main__:INFO:Cur price of NIFTY is: 15281.3
2021-02-15 10:05:16,087:__main__:INFO:Points changed: -13.85
2021-02-15 10:05:16,088:__main__:INFO:repair running...
2021-02-15 10:05:17,090:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.20 -195.0  PE
1   Entry  39842  39842  75  10025850  65.45  63.25  165.0  CE 

2021-02-15 10:05:17,090:__main__:INFO:('15-02-2021 10:05:17', -30.0)
2021-02-15 10:05:19,096:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:21,056:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.70 -232.5  PE
1   Entry  39842  39842  75  10025850  65.45  63.35  157.5  CE 

2021-02-15 10:05:21,056:__main__:INFO:('15-02-2021 10:05:21', -75.0)
2021-02-15 10:05:23,082:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:25,129:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.60 -225.0  PE
1   Entry  39842  39842  75  10025850  65.45  63.15  172.5  CE 

2021-02-15 10:05:25,129:__main__:INFO:('15-02-2021 10:05:25', -52.5)
2021-02-15 10:05:26,010:__main__:INFO:Cur price of NIFTY is: 15278.05
2021-02-15 10:05:26,025:__main__:INFO:Points changed: -17.1
2021-02-15 10:05:26,025:__main__:INFO:repair running...
2021-02-15 10:05:27,130:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:29,162:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.65 -228.75  PE
1   Entry  39842  39842  75  10025850  65.45  63.60  138.75  CE 

2021-02-15 10:05:29,162:__main__:INFO:('15-02-2021 10:05:29', -90.0)
2021-02-15 10:05:31,183:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:33,158:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.50 -217.5  PE
1   Entry  39842  39842  75  10025850  65.45  63.55  142.5  CE 

2021-02-15 10:05:33,158:__main__:INFO:('15-02-2021 10:05:33', -75.0)
2021-02-15 10:05:35,160:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:36,011:__main__:INFO:Cur price of NIFTY is: 15279.2
2021-02-15 10:05:36,011:__main__:INFO:Points changed: -15.95
2021-02-15 10:05:36,011:__main__:INFO:repair running...
2021-02-15 10:05:37,211:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  90.9 -172.50  PE
1   Entry  39842  39842  75  10025850  65.45  63.9  116.25  CE 

2021-02-15 10:05:37,211:__main__:INFO:('15-02-2021 10:05:37', -56.25)
2021-02-15 10:05:39,212:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:41,231:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.3 -202.50  PE
1   Entry  39842  39842  75  10025850  65.45  63.5  146.25  CE 

2021-02-15 10:05:41,231:__main__:INFO:('15-02-2021 10:05:41', -56.25)
2021-02-15 10:05:43,245:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:45,308:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt   ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.9 -247.50  PE
1   Entry  39842  39842  75  10025850  65.45  63.4  153.75  CE 

2021-02-15 10:05:45,308:__main__:INFO:('15-02-2021 10:05:45', -93.75)
2021-02-15 10:05:46,058:__main__:INFO:Cur price of NIFTY is: 15277.75
2021-02-15 10:05:46,063:__main__:INFO:Points changed: -17.4
2021-02-15 10:05:46,065:__main__:INFO:repair running...
2021-02-15 10:05:47,314:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:49,362:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  92.15 -266.25  PE
1   Entry  39842  39842  75  10025850  65.45  63.30  161.25  CE 

2021-02-15 10:05:49,362:__main__:INFO:('15-02-2021 10:05:49', -105.0)
2021-02-15 10:05:51,373:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:53,490:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp     pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.75 -236.25  PE
1   Entry  39842  39842  75  10025850  65.45  63.20  168.75  CE 

2021-02-15 10:05:53,491:__main__:INFO:('15-02-2021 10:05:53', -67.5)
2021-02-15 10:05:55,503:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:05:56,015:__main__:INFO:Cur price of NIFTY is: 15278.45
2021-02-15 10:05:56,030:__main__:INFO:Points changed: -16.7
2021-02-15 10:05:56,030:__main__:INFO:repair running...
2021-02-15 10:05:57,501:__main__:INFO: DF is : 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.50 -217.5  PE
1   Entry  39842  39842  75  10025850  65.45  63.05  180.0  CE 

2021-02-15 10:05:57,502:__main__:INFO:('15-02-2021 10:05:57', -37.5)
2021-02-15 10:05:59,514:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:00,527:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:00,533:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:01,579:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:01,581:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:02,624:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:02,627:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:03,602:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:03,604:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:04,665:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:04,665:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:05,683:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:05,683:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:06,074:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 138, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:06,718:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:06,718:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:07,767:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:07,767:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:08,817:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:08,817:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:09,822:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:09,822:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:10,793:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:10,808:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:11,777:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:11,777:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:12,777:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:12,777:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:13,781:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:13,783:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:14,815:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:14,815:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:15,833:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:15,835:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:16,142:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 138, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:16,836:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:16,836:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:17,820:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:17,835:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:18,794:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:18,794:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:19,761:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:19,761:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:20,795:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:20,795:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:21,908:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:21,908:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:22,925:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:22,925:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:23,992:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:23,992:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:24,995:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:24,995:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:26,040:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:26,042:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:26,140:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 138, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:27,041:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:27,041:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:28,048:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:28,048:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:29,066:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:29,069:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:30,044:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:30,046:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:31,055:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:31,055:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:32,065:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:32,068:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:33,074:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:33,074:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:34,087:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:34,087:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:34,999:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:34,999:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:35,978:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:35,978:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:36,025:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 138, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:36,970:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:36,970:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:37,955:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:37,955:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:38,918:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:38,918:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:39,871:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:39,871:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:40,841:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:40,841:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:41,750:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:41,752:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:42,707:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:42,709:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:43,656:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:43,659:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:44,654:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:44,656:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:45,655:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:45,658:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:46,063:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 138, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:46,623:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:46,625:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:47,604:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:47,604:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:48,562:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:48,564:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:49,491:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:49,492:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:50,465:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:50,467:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:51,464:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:51,465:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:52,461:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:52,464:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:53,450:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:53,451:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:54,456:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:54,458:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:55,387:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:55,387:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:56,003:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 138, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:56,355:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:56,357:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:57,347:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:57,347:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:58,286:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:58,286:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:06:59,258:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:06:59,258:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:00,214:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:00,214:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:01,197:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:01,197:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:02,167:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:02,167:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:03,135:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:03,135:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:04,111:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:04,111:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:05,152:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:05,152:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:06,101:__main__:ERROR:Unable to getSpot from index
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 505, in get_quote
    response = self._post('market.instruments.quotes', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 639, in _post
    return self._request(route, "POST", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 138, in getSpot
    spot_resp = xt.get_quote(
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 508, in get_quote
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:06,164:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:06,164:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:07,136:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:07,136:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:08,082:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:08,085:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:09,136:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:09,136:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:10,169:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:10,171:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:11,134:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:11,134:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:12,147:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:12,149:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:13,087:__main__:ERROR:Failed to get PNL
Traceback (most recent call last):
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 521, in send_unsubscription
    response = self._put('market.instruments.unsubscription', json.dumps(params))
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 643, in _put
    return self._request(route, "PUT", params)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 688, in _request
    raise ex.XTSTokenException(data["description"])
XTConnect.Exception.XTSTokenException: Invalid Token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Downloads\Python\First_Choice_Git\xts\strategy\scripts\Strategy_2_token.py", line 461, in getPnL
    xt.send_unsubscription(Instruments=instruments,xtsMessageCode=1502)
  File "C:\Users\mling\anaconda3\lib\site-packages\xts-0.1-py3.8.egg\XTConnect\Connect.py", line 524, in send_unsubscription
    return response['description']
UnboundLocalError: local variable 'response' referenced before assignment
2021-02-15 10:07:13,087:__main__:INFO:Checking CurPnL for this strategy..
2021-02-15 10:07:14,144:__main__:INFO:Strategy2 Summary: 
   ordrtyp     ss     nn  qq        oo     tt    ltp    pnl oty
0   Entry  47749  47749  75  10025849  88.60  91.50 -217.5  PE
1   Entry  39842  39842  75  10025850  65.45  63.05  180.0  CE
2021-02-15 10:07:14,144:__main__:INFO:Dumping the PnL list to excel sheet..
2021-02-15 10:07:14,894:__main__:INFO:in finally block.. Closing multi threaded func if running..
2021-02-15 10:07:14,894:__main__:INFO:-- Script Ended --
2021-02-15 10:07:14,894:__main__:INFO:-- --------------------------------------------- --
